import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Captur tailwindCSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Hero heading='Capture photography' 
              message='I capture moments in nature and keep them alive.'
        />
    </div>
  )
}





// 1. brisemo nepotrebne HTML elemente koji nam nece trebati
// 2. mijenjamo title - naslov stranice
// 3. importujemo Hero.jsx komponentu unutar div parent elementa
// 4. Hero elementu dodajemo atribute
// 5. 