import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import {SliderData} from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Captur tailwindCSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Hero heading='Capture photography' 
              message='I capture moments in nature and keep them alive.'
        />
        <Slider slides={SliderData}/>
        <Instagram />
    </div>
  );
};





// 1. brisemo nepotrebne HTML elemente koji nam nece trebati
// 2. mijenjamo title - naslov stranice
// 3. importujemo Hero.jsx komponentu unutar div parent elementa
// 4. Hero elementu dodajemo atribute
// 5. Dodajemo Slider komponentu
// 6. Slider komponentu dodajemo slides atribut
// 7. Dodajemo Instagram komponentu